server:
  port: 8080
  host: "127.0.0.1"
queue:
  max_size: "100MB"
log:
  # Log levels: debug, info, warn, error
  level: "debug"
  file_path: "logs/amqp-agent.log"
  max_age: 7        # Log retention days
  rotation_time: 24 # Log rotation hours